CREATE TABLE CUSTOMER
(
	CUSTOMER_ID  INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
	CODE         VARCHAR(8)   NOT NULL,
	NAME         VARCHAR(20)  NOT NULL,
	NAS          VARCHAR(9)   NOT NULL,
	AMOUNT       NUMBER(10,2) NULL,
	BIRTH_DATE   DATETIME     NULL,
	OTHER_DATE   DATETIME     NULL
);
Insert into CUSTOMER
   (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE)
 Values
   (1, 'A', 'Asterix', '111111111', 10.2, '1933-01-01', '2017-04-01');
Insert into CUSTOMER
   (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE)
 Values
   (2, 'B', 'Panoramix', '222222222', 23.14, '1920-02-01', '2017-04-02');
Insert into CUSTOMER
   (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE)
 Values
   (3, 'A', 'Obelix', '333333333', 11.14, '1934-02-03', '2017-04-01');

CREATE TABLE ADDRESS
(
	ADDRESS_ID          INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
	CUSTOMER_ID					INTEGER			 NOT NULL,
	ADDRESS_VALUE				VARCHAR(30)  NOT NULL
);
Insert into ADDRESS
   (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE)
 Values
   (1, 1, '200 rue de La Gaule');
Insert into ADDRESS
   (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE)
 Values
   (2, 1, 'asterix@village.gaulois.fr');
Insert into ADDRESS
   (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE)
 Values
   (3, 2, '1 Stonehenge');
Insert into ADDRESS
   (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE)
 Values
   (4, 3, '204 rue de La Gaule');
