begin
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(CUSTOMER(CUSTOMER_ID))*/ into CUSTOMER (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE) values (1, 'A', 'Asterix', '111111111', 10.2, to_date('1933-01-01', 'YYYY-MM-DD'), to_date('2017-04-01', 'YYYY-MM-DD'));
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(CUSTOMER(CUSTOMER_ID))*/ into CUSTOMER (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE) values (2, 'B', 'Panoramix', '222222222', 23.14, to_date('1920-02-01', 'YYYY-MM-DD'), to_date('2017-04-02', 'YYYY-MM-DD'));
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(CUSTOMER(CUSTOMER_ID))*/ into CUSTOMER (CUSTOMER_ID, CODE, NAME, NAS, AMOUNT, BIRTH_DATE, OTHER_DATE) values (3, 'A', 'Obelix', '333333333', 11.14, to_date('1934-02-03', 'YYYY-MM-DD'), to_date('2017-04-01', 'YYYY-MM-DD'));
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(ADDRESS(ADDRESS_ID))*/ into ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE) values (1, 1, '200 rue de La Gaule');
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(ADDRESS(ADDRESS_ID))*/ into ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE) values (2, 1, 'asterix@village.gaulois.fr');
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(ADDRESS(ADDRESS_ID))*/ into ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE) values (3, 2, '1 Stonehenge');
  insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX(ADDRESS(ADDRESS_ID))*/ into ADDRESS (ADDRESS_ID, CUSTOMER_ID, ADDRESS_VALUE) values (4, 3, '204 rue de La Gaule');
end;
